# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 16:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import oauth.generators


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='expire_at',
            field=models.DateTimeField(default=oauth.generators.grant_expire_at_time, verbose_name='token失效时间'),
        ),
        migrations.AlterField(
            model_name='application',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='应用管理员'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='code',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='授权吗'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='scope',
            field=models.TextField(choices=[('read', '读'), ('read write', '读写')], default='read', max_length=32, verbose_name='权限'),
        ),
    ]
