# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_auto_20160628_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='expire_at',
        ),
    ]
