# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import oauth.generators


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_remove_grant_expire_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='expire_at',
            field=models.DateTimeField(default=oauth.generators.grant_expire_at_time, verbose_name='token失效时间'),
        ),
    ]
