# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import oauth.generators


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0005_auto_20160628_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='code',
            field=models.CharField(db_index=True, default=oauth.generators.generate_grant_code, max_length=255, unique=True, verbose_name='授权码'),
        ),
    ]
