# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-26 08:13
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='邮箱')),
                ('username', models.CharField(blank=True, max_length=32, verbose_name='名称')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='token失效时间')),
                ('access_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='access_token')),
                (
                    'refresh_token',
                    models.CharField(blank=True, max_length=255, null=True, verbose_name='refresh_token')),
                ('provider',
                 models.CharField(choices=[('github', 'Github'), ('qq', 'QQ'), ('coding', 'Coding')], max_length=10,
                                  verbose_name='类别')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
