# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialaccount',
            name='email',
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='uid'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='username',
            field=models.CharField(blank=True, max_length=32, verbose_name='用户名'),
        ),
    ]
